ekf_filter_node:
  ros__parameters:
    frequency: 50.0

    #sensor_timeout: 0.1

    two_d_mode: true

    publish_tf: false

    debug: true

    map_frame: map             
    odom_frame: odom            
    base_link_frame: base_footprint 
    world_frame: odom 

    #x     , y     , z,
    #roll  , pitch , yaw,
    #vx    , vy    , vz,
    #vroll , vpitch, vyaw,
    #ax    , ay    , az

    odom0: mobile_base/odom
    odom0_config: [false, false, false,
                   false, false, false,
                   true,  true,  false,
                   false, false, true,
                   false, false, false]

    imu0: mobile_base/sensors/imu_data
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, true,
                  false, false, false]

    #odom0_differential: true
    #odom0_relative: false
    
    #imu0_differential: true
    #imu0_relative: true
